### ISSUE TITLE
Arrumar banco de dados

### ISSUE THREAD

**Issue by xSPEACHERx** [xSPEACHERx/Projeto-AMIC#1]
Arrumar e postar a versão mais recente do banco de dados

**Comment by xSPEACHERx** [comment]
Alterações no BD:

-> Na tabela "reporte", acrescentar o atributo "título do problema"

-> Na tabela "computador", acrescentar atributo "status" (operando/não operando), atributo "relatórios pendentes" e atributo "feedbacks".

-> Na tabela "Técnico", acrescentar atributo "Siape", tipo VARCHAR de 8 dígitos.

-> Na tabela "Técnico", acrescentar período do tipo VARCHAR (matutino, vespertino, noturno ou integral).

-> Na tabela "usuário", acrescentar atributo "matrícula", VARCHAR de 16 dígitos.

-> Ajustar os campos da Tabela "REPORTE" Para se adequar a tabela da pagina "Modelo maquina.html"


Arquivo MER Corrido pelo professor:
[Diego Nunes de Oliveira_489997_assignsubmission_file_ (1).zip](https://github.com/xSPEACHERx/Projeto-AMIC/files/9309715/Diego.Nunes.de.Oliveira_489997_assignsubmission_file_.1.zip)

**Comment by VictorHSM24** [comment]
[EER Amic.zip](https://github.com/xSPEACHERx/Projeto-AMIC/files/9330668/EER.Amic.zip)

**Comment by VictorHSM24** [comment]
**Issue reaberta para envio do EER corrigido**

[EER AMIC.zip](https://github.com/xSPEACHERx/Projeto-AMIC/files/9412075/EER.AMIC.zip)
